// P8/API_study_task2/src/views/ProductView.jsx
import { useEffect, useState } from "react";
import { getProduct } from "../api";

function ProductView({ productId, goBack, onBuy }) {
  const [product, setProduct] = useState();
  const [qty,setQty] = useState(1);

  const [problem, setProblem] = useState("");


  useEffect(() => {
    getProduct(productId)
      .then(res => {
        setProduct(res.data);
      })
      .catch(err => {
        setProblem(err.message);
      });
  }, [productId]);


  if (problem) {
    return (
      <div className="mt-4">
        <p>Problem loading product: {problem}</p>

        <button onClick={goBack} className="border px-1 mt-3">
          Back
        </button>
      </div>
    );
  }

  if (!product)
    return <p>loading...</p>;


  const maxQty = Math.min(5, product.available_quantity);


  function quantityChanged(e) {
    let value = Number(e.target.value);

    if (value < 1)
      value = 1;

    if (value > maxQty) value = maxQty;

    setQty(value);
  }


  return (
    <div className="mt-4">
      <button onClick={goBack}>
        Back to products
      </button>

      <h2 className="font-bold mt-4 text-xl">
        {product.name}
      </h2>

      <img
        src={product.image_url}
        width="300"
        alt={product.name}
        className="mt-2"
      />

      <p className="mt-3">
        {product.description}
      </p>

      <p>
        Price: {product.price} {product.currency}
      </p>


      <h3 className="mt-4 font-bold">Features</h3>

      <ul className="list-disc ml-7">
        {product.features.map((feature, i) =>
          <li key={i}>{feature}</li>
        )}
      </ul>


      <p className="mt-4">
        Available: {product.available_quantity}
      </p>


      {product.available_quantity === 0 ? (
        <p>Out of stock</p>
      ) : (
        <div>
          <label htmlFor="quantity">
            Quantity
          </label>

          <input
            id="quantity"
            className="border ml-2 w-16"
            type="number"
            min="1"
            max={maxQty}
            value={qty}
            onChange={quantityChanged}
          />

          <br/>

          <button
            className="px-3 border mt-4 py-1"
            onClick={() => onBuy(product, qty)}
          >
            Buy now
          </button>
        </div>
      )}
    </div>
  );
}

export default ProductView;

// P9/REST-API-IMPLEMENTATION-1/src/views/ProductView.vue
<script setup>
import { onMounted, ref } from "vue"
import { useRoute, useRouter } from "vue-router"
import { getProduct } from "../api"

const route = useRoute()
const router = useRouter()

const product = ref(null)
const quantity = ref(1)
const error = ref("")
const loading = ref(true)

onMounted(async () => {
  try {
    const response = await getProduct(route.params.id)
    product.value = response.data
  } catch (e) {
    error.value = e.message
  }

  loading.value = false
})

function buy() {
  const max = Math.min(5, product.value.available_quantity)

  if (quantity.value < 1 || quantity.value > max) {
    error.value = `Quantity must be between 1 and ${max}`
    return
  }

  router.push(
    `/checkout?product=${product.value.id}&quantity=${quantity.value}`
  )
}
</script>

<template>
  <p v-if="loading">Loading...</p>
  <p v-if="error" style="color: darkred">{{ error }}</p>

  <div v-if="product">
    <div
      style="
        display: flex;
        gap: 30px;
        margin-top: 20px;
        background: white;
        padding: 20px;
        border: 1px solid #aaa;
      "
    >
      <div style="width: 45%">
        <img
          :src="product.image_url"
          :alt="product.name"
          style="
            width: 100%;
            max-height: 350px;
            object-fit: contain;
          "
        >
      </div>

      <div style="flex: 1">
        <h1 style="margin-top: 0">
          {{ product.name }}
        </h1>

        <p>
          {{ product.description }}
        </p>

        <h2 style="margin: 20px 0">
          {{ product.price }} {{ product.currency }}
        </h2>

        <h3>Features</h3>

        <ul>
          <li
            v-for="feature in product.features"
            :key="feature"
          >
            {{ feature }}
          </li>
        </ul>

        <p style="margin-top: 20px">
          <strong>Available:</strong>
          {{ product.available_quantity }}
        </p>

        <div
          v-if="product.available_quantity > 0"
          style="
            margin-top: 20px;
            padding-top: 15px;
            border-top: 1px solid #ccc;
          "
        >
          <label>
            Quantity
            <input
              v-model.number="quantity"
              type="number"
              min="1"
              :max="Math.min(5, product.available_quantity)"
              style="
                width: 60px;
                padding: 7px;
                margin-left: 8px;
              "
            >
          </label>

          <button
            @click="buy"
            style="
              display: block;
              margin-top: 15px;
              padding: 10px 20px;
              background: #536a92;
              color: white;
              border: 0;
              cursor: pointer;
            "
          >
            Buy Now
          </button>
        </div>

        <p v-else style="color: darkred">
          Out of stock
        </p>
      </div>
    </div>
  </div>
</template>
