// P10/INKandSMOKE/src/pages/Products.jsx
import { useEffect, useState } from "react";
import { getProducts } from "../api";

export default function Products() {
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    getProducts()
      .then((response) => {
        setProducts(response.data);
      })
      .catch((err) => {
        setError(err.message);
      })
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <main className="max-w-6xl mx-auto p-6">
        <p className="text-slate-500">Loading products...</p>
      </main>
    );
  }

  if (error) {
    return (
      <main className="max-w-6xl mx-auto px-6 py-8">
        <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-red-700">
          {error}
        </div>
      </main>
    );
  }

  return (
    <main className="max-w-6xl mx-auto py-8 px-5">
      <div className="mb-7">
        <h1 className="text-3xl font-bold">Shop</h1>


      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
        {products.map((product) => (
          <div
            key={product.id}
            className="bg-white rounded-xl border p-5 border-slate-200 shadow-sm p-5"
          >
            <img
              src={product.image_url}
              alt=""
              className="w-full h-48 object-contain bg-slate-50 rounded-lg mb-4"
            />

            <h2 className="font-semibold text-lg">{product.name}</h2>

            <div className="font-bold text-xl mt-2 mb-3">
              {product.price}{" "}
              <span className="text-sm font-normal text-slate-500">
                {product.currency}
              </span>
            </div>

            <div className="mb-5">
              {product.features.map((feature) => (
                <div
                  key={feature}
                  className="text-sm text-slate-600 mb-1"
                >
                  • {feature}
                </div>
              ))}
            </div>

            <a
              href={`/product/${product.id}`}
              className="inline-block rounded-md text-white bg-slate-900 px-4 py-2 text-sm font-medium px-4"
            >
              Check it Out
            </a>
          </div>
        ))}
      </div>
    </main>
  );
}

// P7/peter-study-task-1/src/app/pages/products.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';

// @ts-ignore
import { getProducts } from '../api.js';

@Component({
  selector: 'app-products',
  standalone: true,
  imports: [
    CommonModule,
    RouterLink
  ],
  template: `
    <h1>Products</h1>

    <p *ngIf="loading">Loading products...</p>

    <p *ngIf="error" class="text-red-700">
      {{ error }}
    </p>

    <div class="grid gap-6 md:grid-cols-2 mt-5" *ngIf="!loading">
      <article
        *ngFor="let product of products"
        class="border p-4 bg-white"
      >
        <img
          [src]="product.image_url"
          [alt]="product.name"
          class="max-w-xs w-full mb-3"
        >

        <h2>{{ product.name }}</h2>

        <p>
          {{ product.price | number:'1.2-2' }}
          {{ product.currency }}
        </p>

        <ul>
          <li *ngFor="let feature of product.features">
            {{ feature }}
          </li>
        </ul>

        <p class="mt-4">
          <a [routerLink]="['/product', product.id]">
            View Product
          </a>
        </p>
      </article>
    </div>
  `
})
export class ProductsComponent implements OnInit {
  products: any[] = [];
  loading = true;
  error = '';

  constructor(private cdr: ChangeDetectorRef) {}

  async ngOnInit() {
    try {
      const response = await getProducts();

      console.log('API response:', response);

      this.products = response.data;
    } catch (err) {
      console.error(err);

      this.error = err instanceof Error
        ? err.message
        : 'Could not load products.';
    } finally {
      this.loading = false;

      this.cdr.detectChanges();
    }
  }
}
