// P1/ecommerce_2/src/pages/Products.jsx
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getProducts } from "../api";

function Products() {
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    async function loadProducts() {
      try {
        const response = await getProducts();
        setProducts(response.data);
      } catch {
        setError(true);
      }

      setLoading(false);
    }

    loadProducts();
  }, []);

  if (loading) {
    return (
      <div className="page">
        <p>Loading products...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="page" role="alert">
        <h1>Products</h1>
        <p>Products could not be loaded.</p>
      </div>
    );
  }

  return (
    <div className="page">
      <h1>Products</h1>

      <div className="product-list">
        {products.map((product) => (
          <article className="product-card" key={product.id}>
            <img
              src={product.image_url}
              alt={product.name}
              className="product-image"
            />

            <h2>{product.name}</h2>

            <p>{product.description}</p>

            <div className="product-price">
              {product.currency} {product.price}
            </div>

            <Link
              className="button"
              to={`/products/${product.id}`}
            >
              View product
            </Link>
          </article>
        ))}
      </div>
    </div>
  );
}

export default Products;

// P7/peter-study-task-1/src/app/pages/products.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';

// @ts-ignore
import { getProducts } from '../api.js';

@Component({
  selector: 'app-products',
  standalone: true,
  imports: [
    CommonModule,
    RouterLink
  ],
  template: `
    <h1>Products</h1>

    <p *ngIf="loading">Loading products...</p>

    <p *ngIf="error" class="text-red-700">
      {{ error }}
    </p>

    <div class="grid gap-6 md:grid-cols-2 mt-5" *ngIf="!loading">
      <article
        *ngFor="let product of products"
        class="border p-4 bg-white"
      >
        <img
          [src]="product.image_url"
          [alt]="product.name"
          class="max-w-xs w-full mb-3"
        >

        <h2>{{ product.name }}</h2>

        <p>
          {{ product.price | number:'1.2-2' }}
          {{ product.currency }}
        </p>

        <ul>
          <li *ngFor="let feature of product.features">
            {{ feature }}
          </li>
        </ul>

        <p class="mt-4">
          <a [routerLink]="['/product', product.id]">
            View Product
          </a>
        </p>
      </article>
    </div>
  `
})
export class ProductsComponent implements OnInit {
  products: any[] = [];
  loading = true;
  error = '';

  constructor(private cdr: ChangeDetectorRef) {}

  async ngOnInit() {
    try {
      const response = await getProducts();

      console.log('API response:', response);

      this.products = response.data;
    } catch (err) {
      console.error(err);

      this.error = err instanceof Error
        ? err.message
        : 'Could not load products.';
    } finally {
      this.loading = false;

      this.cdr.detectChanges();
    }
  }
}
