// P7/peter-study-task-2/src/app/pages/checkout.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectorRef,
  Component,
  OnInit
} from '@angular/core';

import { FormsModule, NgForm } from '@angular/forms';
import {
  ActivatedRoute,
  Router,
  RouterLink
} from '@angular/router';

// @ts-ignore
import { createOrder, getProduct } from '../api.js';


@Component({
  selector: 'app-checkout',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  template: `
    <h1>Checkout</h1>

    <p
      *ngIf="loading"
      role="status"
      aria-live="polite"
    >
      Loading checkout...
    </p>

    <div
      *ngIf="loadError"
      role="alert"
      aria-live="assertive"
      class="text-red-700"
    >
      {{ loadError }}
    </div>


    <div *ngIf="product && !loading">
      <section
        class="p-4 border mb-8"
        aria-labelledby="cart-heading"
      >
        <h2 id="cart-heading">Your cart</h2>

        <p>
          <strong>{{ product.name }}</strong>
        </p>

        <p>Quantity: {{ quantity }}</p>

        <p>
          Total:
          <strong>
            {{ total | number:'1.2-2' }}
            {{ product.currency }}
          </strong>
        </p>

        <a [routerLink]="['/product', product.id]">
          Change quantity
        </a>

        <p
          *ngIf="!quantityValid"
          role="alert"
          class="text-red-700"
        >
          This quantity is not available. Go back and choose a valid quantity.
        </p>
      </section>


      <form
        #checkoutForm="ngForm"
        (ngSubmit)="submit(checkoutForm)"
      >
        <fieldset>
          <legend>Customer information</legend>

          <div class="mb-3">
            <label for="fullName">Full name</label><br>

            <input
              id="fullName"
              name="fullName"
              [(ngModel)]="customer.full_name"
              type="text"
              required
              maxlength="100"
              autocomplete="name"
              class="p-1 border w-full max-w-md"
            >
          </div>

          <div>
            <label for="email">Email address</label><br>

            <input
              id="email"
              name="email"
              [(ngModel)]="customer.email"
              type="email"
              required
              autocomplete="email"
              class="border max-w-md p-1 w-full"
            >
          </div>
        </fieldset>


        <fieldset class="mt-7">
          <legend>Delivery address</legend>

          <div>
            <label for="address">Address line</label><br>

            <input
              id="address"
              name="address"
              type="text"
              [(ngModel)]="delivery.address_line"
              required
              maxlength="200"
              autocomplete="street-address"
              class="w-full p-1 max-w-md border"
            >
          </div>

          <div class="mt-3">
            <label for="city">Town or city</label><br>

            <input
              id="city"
              name="city"
              [(ngModel)]="delivery.city"
              required
              maxlength="100"
              autocomplete="address-level2"
              class="border w-full max-w-md p-1"
            >
          </div>

          <div class="mt-3">
            <label for="postcode">Postal code</label><br>

            <input
              id="postcode"
              name="postcode"
              type="text"
              [(ngModel)]="delivery.postcode"
              required
              maxlength="20"
              autocomplete="postal-code"
              class="border p-1 w-full max-w-md"
            >
          </div>
        </fieldset>


        <fieldset class="mt-7">
          <legend>Payment information</legend>

          <div>
            <label for="cardName">
              Cardholder name
            </label><br>

            <input
              id="cardName"
              name="cardName"
              [(ngModel)]="payment.cardholder_name"
              required
              maxlength="100"
              autocomplete="cc-name"
              class="w-full border p-1 max-w-md"
            >
          </div>

          <div class="mt-3">
            <label for="cardNumber">
              Card number
            </label><br>

            <input
              id="cardNumber"
              name="cardNumber"
              type="text"
              [(ngModel)]="payment.card_number"
              required
              minlength="12"
              maxlength="23"
              autocomplete="cc-number"
              inputmode="numeric"
              aria-describedby="payment-help"
              class="border p-1 max-w-md w-full"
            >
          </div>

          <div class="mt-3">
            <label for="expiry">
              Expiry date (MM/YY)
            </label><br>

            <input
              id="expiry"
              name="expiry"
              [(ngModel)]="payment.expiry_date"
              required
              type="text"
              pattern="[0-9]{2}/[0-9]{2}"
              placeholder="12/30"
              autocomplete="cc-exp"
              aria-describedby="expiry-help"
              class="p-1 border"
            >

            <p id="expiry-help">
              Enter the expiry as MM/YY, for example 12/30.
            </p>
          </div>

          <div class="mt-3">
            <label for="securityCode">CVV</label><br>

            <input
              id="securityCode"
              name="securityCode"
              type="password"
              [(ngModel)]="payment.security_code"
              required
              pattern="[0-9]{3,4}"
              maxlength="4"
              inputmode="numeric"
              autocomplete="cc-csc"
              aria-describedby="cvv-help"
              class="border p-1"
            >

            <p id="cvv-help">
              Enter three or four digits.
            </p>
          </div>
        </fieldset>


        <div
          *ngIf="error"
          role="alert"
          aria-live="assertive"
          class="text-red-700 mt-5"
        >
          <p>{{ error }}</p>

          <ul *ngIf="suggestions.length">
            <li *ngFor="let suggestion of suggestions">
              {{ suggestion }}
            </li>
          </ul>
        </div>

        <button
          type="submit"
          [disabled]="submitting || !quantityValid"
          class="mt-6 px-5 border py-2"
        >
          {{ submitting ? 'Submitting...' : 'Place Order' }}
        </button>

        <p
          *ngIf="submitting"
          role="status"
          aria-live="polite"
        >
          Submitting your order...
        </p>
      </form>
    </div>
  `
})
export class CheckoutComponent implements OnInit {

  product: any = null;
  quantity = 0;

  loading = true;
  submitting = false;

  error = '';
  loadError = '';
  suggestions: string[] = [];


  customer = {
    full_name: '',
    email: ''
  };

  delivery = {
    address_line: '',
    city: '',
    postcode: ''
  };

  payment = {
    cardholder_name: '',
    card_number: '',
    expiry_date: '',
    security_code: ''
  };


  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private cdr: ChangeDetectorRef
  ) {}


  get total() {
    if (!this.product) return 0;

    return this.product.price * this.quantity;
  }

  get quantityValid() {
    if (!this.product)
      return false;

    const max = Math.min(
      this.product.available_quantity,
      5
    );

    return Number.isInteger(this.quantity)
      && this.quantity >= 1
      && this.quantity <= max;
  }


  async ngOnInit() {
    const id = Number(
      this.route.snapshot.paramMap.get('id')
    );

    this.quantity = Number(
      this.route.snapshot.queryParamMap.get('quantity')
    );

    if (!Number.isInteger(id)) {
      this.loadError = 'Invalid product.';
      this.loading = false;

      this.cdr.detectChanges();
      return;
    }

    try {
      const response = await getProduct(id);

      this.product = response.data;
    }
    catch (err) {
      console.error(err);

      this.loadError = err instanceof Error
        ? err.message
        : 'Checkout could not be loaded.';
    }
    finally {
      this.loading = false;
      this.cdr.detectChanges();
    }
  }


  async submit(form: NgForm) {
    this.error = '';
    this.suggestions = [];

    if (form.invalid) {
      form.control.markAllAsTouched();

      this.error =
        'Some of the information entered is missing or invalid. Check the form and try again.';

      return;
    }

    if (!this.quantityValid) {
      this.error =
        'The selected quantity is no longer available. Choose another quantity.';

      return;
    }


    const order = {
      product_id: this.product.id,
      quantity: this.quantity,

      customer: {
        full_name: this.customer.full_name,
        email: this.customer.email
      },

      delivery_address: {
        address_line: this.delivery.address_line,
        city: this.delivery.city,
        postcode: this.delivery.postcode
      },

      payment: {
        cardholder_name: this.payment.cardholder_name,
        card_number: this.payment.card_number,
        expiry_date: this.payment.expiry_date,
        security_code: this.payment.security_code
      }
    };


    this.submitting = true;
    this.cdr.detectChanges();

    try {
      const response = await createOrder(order);

      this.submitting = false;
      this.cdr.detectChanges();

      await this.router.navigate([
        '/order',
        response.data.id
      ]);
    }
    catch (err: any) {
      console.error(err);

      this.error = err instanceof Error
        ? err.message
        : 'There was a problem completing the order.';

      const nudges = err?.accessibility?.nudges || [];

      this.suggestions = nudges
        .filter((nudge: any) =>
          nudge.success_criterion === '3.3.3'
        )
        .flatMap((nudge: any) =>
          Array.isArray(nudge.values)
            ? nudge.values
            : []
        );

      this.submitting = false;
      this.cdr.detectChanges();
    }
  }
}

// P6/study_peter_2/src/routes/checkout/+page.svelte
<script>
 import { onMount } from 'svelte';
 import { page } from '$app/state';
 import { goto } from '$app/navigation';
 import { getProduct, createOrder } from '$lib/api.js';

 let product = null;
 let quantity = 1;
 let error = '';
 let suggestions = [];
 let sending = false;

 let form = {
   full_name:'', email:'', address_line:'', city:'', postcode:'',
   cardholder_name:'', card_number:'', expiry_date:'', security_code:''
 };

 $: total = product ? product.price * quantity : 0;

 onMount(async () => {
   const id = page.url.searchParams.get('product');
   quantity = Number(page.url.searchParams.get('qty')) || 1;
   if (!id) { error = 'No product selected.'; return; }

   try {
     const response = await getProduct(id);
     product = response.data;
     quantity = Math.min(Math.max(quantity, 1), 5, product.available_quantity);
   } catch (e) {
     error = e.data?.detail || e.message;
   }
 });

 function readApiError(e) {
   suggestions = [];
   const body = e.data;

   if (Array.isArray(body?.detail)) {
     error = body.detail.map((x) => x.msg || 'Invalid input').join('. ');
   } else error = body?.detail || e.message;

   const nudges = body?.accessibility?.nudges || [];
   suggestions = nudges
     .filter((n) => n.success_criterion === '3.3.3' || n.type === 'error-suggestion')
     .map((n) => n.message || n.values?.[0])
     .filter(Boolean);
 }

 async function submitOrder() {
   sending = true; error = ''; suggestions = [];

   const order = {
     product_id: product.id,
     quantity,
     customer: { full_name: form.full_name, email: form.email },
     delivery_address: { address_line: form.address_line, city: form.city, postcode: form.postcode },
     payment: {
       cardholder_name: form.cardholder_name,
       card_number: form.card_number,
       expiry_date: form.expiry_date,
       security_code: form.security_code
     }
   };

   try {
     const result = await createOrder(order);
     goto(`/order/${result.data.id}`);
   } catch (e) {
     readApiError(e);
     sending = false;
   }
 }
</script>

<h1>Checkout</h1>
<p>Complete the details below to place the order.</p>

{#if error}
  <div class="error" role="alert">
    <strong>There was a problem.</strong>
    <div>{error}</div>
    {#if suggestions.length}
      <ul>{#each suggestions as suggestion}<li>{suggestion}</li>{/each}</ul>
    {/if}
  </div>
{/if}

{#if product}
  <section class="summary" aria-labelledby="order-summary-title">
    <h2 id="order-summary-title">Order summary</h2>
    <p><strong>{product.name}</strong> × {quantity}</p>
    <p>Total: <strong>{product.currency} {total.toFixed(2)}</strong></p>
  </section>

  <form onsubmit={(event) => { event.preventDefault(); submitOrder(); }}>
    <h2>Customer information</h2>
    <label>Full name <input required autocomplete="name" bind:value={form.full_name} /></label>
    <label>Email address <input required type="email" autocomplete="email" bind:value={form.email} /></label>

    <h2>Delivery address</h2>
    <label class="wide">Address line <input required autocomplete="street-address" bind:value={form.address_line} /></label>
    <label>Town or city <input required autocomplete="address-level2" bind:value={form.city} /></label>
    <label>Postal code <input required autocomplete="postal-code" bind:value={form.postcode} /></label>

    <h2>Payment</h2>
    <label>Cardholder name <input required autocomplete="cc-name" bind:value={form.cardholder_name} /></label>
    <label>Card number <input required minlength="12" maxlength="23" inputmode="numeric" autocomplete="cc-number" bind:value={form.card_number} /></label>
    <label>Expiry date <input required pattern="\d{2}/\d{2}" placeholder="MM/YY" autocomplete="cc-exp" bind:value={form.expiry_date} /></label>
    <label>CVV <input required pattern="\d{3,4}" maxlength="4" inputmode="numeric" autocomplete="cc-csc" bind:value={form.security_code} /></label>

    <button class="wide" disabled={sending}>{sending ? 'Placing order...' : 'Place order'}</button>
  </form>
{/if}
